modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="testmod"
version="1.0"
displayName="Test Mod"
credits="Me" 
authors="Bindy for making the mod."
description='''
A test mod by bindy 
'''